config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	namespace :admin do
    root 'page#index'
	  get 'no_access_right', controller: :page, action: :no_access_right
	  match 'login', controller: :page, action: :login, via: [:get, :post]
	  get 'logout', controller: :page, action: :logout
  end

  scope module: :front do
  	root 'page#index'
  end
end

app/views/admin/page/login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../images/favicon.ico">

  <title>JMEC-SEMINAR LogIn</title>

  <%= stylesheet_link_tag 'admin/application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'admin/application' %>

  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
  <%= yield :stylesheets %>

</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-box-body">
    <%= form_tag admin_login_path, method: :post do %>
        <div class="form-group has-feedback">
          <%= text_field :admin_user, :email, class:'form-control', placeholder: 'メールアドレス' %>
          <span class="ion ion-email form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <%= password_field :admin_user, :password ,class: 'form-control', placeholder: 'パスワード' %>
          <span class="ion ion-locked form-control-feedback"></span>
        </div>
        <div class="row">
          <div class="col-12 text-center">
            <%= submit_tag "ログイン", class:'btn btn-info btn-block btn-flat margin-top-10' %>
          </div>
        </div>
    <% end %>
    <div class="margin-top-30 text-center"></div>
  </div>
</div>
</body>
</html>

app/views/admin/page/no_access_right.html.erb
アクセス権がありません